### ISSUE TITLE
Variable Name Typo in generate_cov_openai.py

### ISSUE THREAD

**Issue by HaomiaoPan** [LLM4SoftwareTesting/TestEval#1]
I found a typo in the variable name within the `generate_cov_openai.py` file. The variable `desc_noeg` should be `desc`. This typo will lead to errors during execution.

**Details:**

- **File:** `generate_cov_openai.py`
- **Current Code:**
    ```python
    prompt=prompt_template.format(lang='python', program=code, description=desc_noeg, func_name=func_name)
    ```
- **Corrected Code:**
    ```python
    prompt=prompt_template.format(lang='python', program=code, description=desc, func_name=func_name)
    ```

**Comment by jacobwwh** [comment]
I have corrected `generate_cov_openai.py`. Thanks for pointing out!
