### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'prompt/system_exec.txt'

### ISSUE THREAD

**Issue by strongcc** [LLM4SoftwareTesting/TestEval#6]
when I run gen_linecov_cot_xx.py

throw Error exception:
FileNotFoundError: [Errno 2] No such file or directory: 'prompt/system_exec.txt'

should I modify it to prompt/system.txt   as other py?

**Comment by jacobwwh** [comment]
I have just uploaded 'prompt/system_exec.txt'. Thank you for pointing out.
