### ISSUE TITLE
NameError: name 'desc_noeg' is not defined

### ISSUE THREAD

**Issue by strongcc** [LLM4SoftwareTesting/TestEval#7]
The Error below occured in generate_pathcov_xx and generate_targetcov_xx.py

prompt=prompt_template_branch.format(lang='python', program=code_input, description=desc_noeg, func_name=func_name, branch=branch_input)
NameError: name 'desc_noeg' is not defined

---
should I modify desc_noeg to desc ?

**Comment by jacobwwh** [comment]
Yes, you can change these.

**Comment by strongcc** [comment]
ok ,thank you!!
