### ISSUE TITLE
ImportError: cannot import name 'remove_examples' from 'data_utils'

### ISSUE THREAD

**Issue by strongcc** [LLM4SoftwareTesting/TestEval#9]
generate_targetcov_openai.py", line 9, in <module>
    from data_utils import read_jsonl, write_jsonl, add_lineno, remove_examples
ImportError: cannot import name 'remove_examples' from 'data_utils' 

In data_utils.py I couldn't find function named remove_examples. So this should I delete ?  （It doesn't affect the running）

**Comment by jacobwwh** [comment]
Fixed by removing 'remove_examples'.
